site_name: marimo_dev
site_description: Documentation for marimo_dev
docs_dir: ../docs
site_dir: ../_mkdocs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: ["."]
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Marimo Notebooks: notebooks.md
  - Reports: reports.md
