# This workflow performs maintenance tasks for the repository
# It runs automatically when changes are pushed to any branch

name: MAINTENANCE

# Defines when the workflow will run
on:
  push

# Define the permissions needed for this workflow
permissions:
  contents: 'read'  # Read-only access to repository contents

jobs:
  # Run tests on the marimo notebooks
  test:
    # Use a reusable workflow from the marimushka repository
    uses: jebel-quant/marimushka/.github/workflows/test.yml@v0.1.4
    with:
      # Specify the directory containing the notebooks to test
      notebook-dir: notebooks
