name: pre-commit

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: tschm/cradle/actions/pre-commit@v0.1.57

  deptry:
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.57

      - uses: tschm/cradle/actions/deptry@main
        with:
          source-folder: notebooks
          options: '--per-rule-ignores "DEP002=clarabel|kaleido"'
