# This workflow handles version bumping and publishing of the project
# It can only be triggered manually through the GitHub UI

name: Bump version and publish

# Define when this workflow will run
on:
  workflow_dispatch:  # Manual trigger only

# Define the default permissions needed for this workflow
permissions:
  contents: write  # Write access to repository contents for tagging and publishing

jobs:
  # This job creates a new version tag for the repository
  tagging:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Generate a new version tag based on conventional commits
      - name: Generate Tag
        uses: tschm/cradle/actions/tag@v0.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

  # This job exports marimo notebooks to static HTML/WebAssembly
  publish:
    needs: tagging  # This job runs after the tagging job completes successfully
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      # Export notebooks and publish them
      - uses: jebel-quant/marimushka@v0.1.4
        with:
          notebooks: notebooks         # Directory containing the notebooks to export as plain html notebooks
          apps: notebooks              # Directory containing the notebooks to export as apps
          # notebooks_wasm: notebooks    # Directory containing the notebooks to export as interactive notebooks

  book:
    runs-on: ubuntu-latest
    needs: publish

    environment:
      name: github-pages

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: tschm/cradle/actions/book@v0.2.1
        with:
          title: "Marimo DevContainer"
          links: |
            {
              "Notebooks": "./marimushka"
            }
